Repository chronosphereio/calyptia-core-product-release, pull requests merged in 2023-12, with the labels that each got.

#129 ci: update to latest Calyptia versions
  component-config.json
Labels: ci, automerge

#132 ci: update to latest Calyptia versions
  component-config.json
Labels: ci, automerge

#135 workflows: add fleet tests
  .github/workflows/call-fleet-integration-tests.yaml
  .github/workflows/ci.yml
Labels: disable-e2e-tests, enable-fleet-tests

#139 workflows: add self-hosted stack VM creation
  .github/actions/debug-cluster/action.yaml
  .github/workflows/call-create-self-hosted-stack.yaml
  .github/workflows/call-delete-self-hosted-stack.yaml
  .github/workflows/create-self-hosted-stack.yaml
  scripts/create-self-hosted-gcp-vm.sh
Labels: disable-e2e-tests

#143 workflows: ignore expected failures in API tests
  .github/workflows/create-self-hosted-stack.yaml
Labels: disable-e2e-tests

#144 workflows: support multiple product updates
  .github/workflows/update-product-version.yaml
  scripts/update-versions.sh
Labels: disable-e2e-tests

#147 ci: update to latest Calyptia versions
  .github/workflows/update-product-version.yaml
  component-config.json
Labels: ci, automerge

#150 ci: update to latest Calyptia versions
  component-config.json
Labels: ci, automerge
